### ISSUE TITLE
Usability issue

### ISSUE THREAD

**Issue by danbst** [alexvicegrab/tangoLyricsDB#5]
Currently viewing song (e.g. http://www.tangotranslation.com/songs/211) you see several columns, of which the largest is called "Translator"

I've clicked several times on "Translator" link, thinking that was link to translation by that translator. Currently it leads to translator metadata, which is rarely used information. My point is that the largest column must be direct link to translation. That is much more intuitive (for me, lol)

**Comment by kaceo** [comment]
I think the layout is confusing because we click on the song title on front page, we expect to see some lyrics (original or translated) but the system returns metadata instead.  Perhaps it is possible to store the first line of the translation from the translator's link?    Sometimes we may not be 100% sure of the name of the song, so without any part of the lyrics/singer/artist to confirm, it is not likely to continue clicking to deeper levels of links.

**Comment by alexvicegrab** [comment]
Hi Danbst,

I see your point, though the column is labelled as translator, and it is useful to have a way of going to the translator page, though a more useful link might be to the translator's collection of translations (as when clicking on the looking glass in the individual Translator page).

I also agree that the link to the site could be a bit more visible, perhaps with a bit of text and brighter colour.

**Comment by alexvicegrab** [comment]
Hi Kaceo,

Well, the problem here is that each song has multiple translations, often in different languages, so it's difficult to implement a direct-to-translation link without artificially prioritising one translation over another.

Regarding storing the first line of the translation (or original lyrics), that's quite a hard problem to solve, as one would need to program the database to enter the page the translation is from and select the correct block of HTML and find the first line. I'm also not sure how useful it is to most users of the site. Perhaps if hovering on the link could bring up the entire translation to bear, that might be more informative still, but faces the same challenges.

**Comment by danbst** [comment]
>  ...though a more useful link might be to the translator's collection of translations
no, this issue is about "...though a more useful link might be to the song translation itself, not translator meta-info"

But let's close, the site is useful even without this
